APPROVE_GUARD_ADDRESS=$APPROVE_GUARD_ADDRESS
SPENDER_ADDRESS=$CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS

echo "APPROVE_GUARD_ADDRESS: $APPROVE_GUARD_ADDRESS"
echo "SPENDER_ADDRESS: $SPENDER_ADDRESS"
echo "RPC_URL: $RPC_URL"

cast send $APPROVE_GUARD_ADDRESS "setSpender(address,bool)" $SPENDER_ADDRESS true --rpc-url $RPC_URL --private-key $PRIVATE_KEY