TARGET_ADDRESS=$CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS

echo "CURRENT_VAULT_ADDRESS: $CURRENT_VAULT_ADDRESS"
echo "TARGET_ADDRESS: $TARGET_ADDRESS"
echo "RPC_URL: $RPC_URL"

cast send $CURRENT_VAULT_ADDRESS "setTrustedTarget(address,bool)" $TARGET_ADDRESS true --rpc-url $RPC_URL --private-key $PRIVATE_KEY