## Load hub config
source config/sei/usdc/hub/main.sh


export CURRENT_REMOTE=eth
export CURRENT_BRIDGE=lz
export INTERACT_FROM_HUB=true



REMOTE_UPPER=$(echo "$CURRENT_REMOTE" | tr '[:lower:]' '[:upper:]')


# source config/sei/usdc/remotes/hub/main.sh
# source config/sei/usdc/hub/$CURRENT_BRIDGE.sh

# source config/sei/usdc/remotes/hub/$CURRENT_BRIDGE.sh

# source config/sei/usdc/remotes/$CURRENT_REMOTE/main.sh
# source config/sei/usdc/remotes/$CURRENT_REMOTE/$CURRENT_BRIDGE.sh


eval "export REMOTE_SUB_VAULT_ADDRESS=\$${REMOTE_UPPER}_SUB_VAULT_ADDRESS"
eval "export REMOTE_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS=\$${REMOTE_UPPER}_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS"
eval "export REMOTE_OFT_ADDRESS=\$${REMOTE_UPPER}_OFT_ADDRESS"
eval "export REMOTE_ASSET_ADDRESS=\$${REMOTE_UPPER}_ASSET_ADDRESS"
eval "export REMOTE_AUTHORITY_ADDRESS=\$${REMOTE_UPPER}_AUTHORITY_ADDRESS"
eval "export REMOTE_EID=\$${REMOTE_UPPER}_EID"


## Current setting 
if [ "$INTERACT_FROM_HUB" = true ]; then
    export CURRENT_VAULT_ADDRESS=$VAULT_ADDRESS
    export CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS=$CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS
    export CURRENT_OFT_ADDRESS=$OFT_ADDRESS
    export CURRENT_ASSET_ADDRESS=$ASSET_ADDRESS
    

    export DEST_EID=$REMOTE_EID
    export DEST_VAULT_ADDRESS=$REMOTE_SUB_VAULT_ADDRESS
else
    export CURRENT_VAULT_ADDRESS=$REMOTE_SUB_VAULT_ADDRESS
    export CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS=$REMOTE_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS
    export CURRENT_OFT_ADDRESS=$REMOTE_OFT_ADDRESS
    export CURRENT_ASSET_ADDRESS=$REMOTE_ASSET_ADDRESS
    export CURRENT_DST_EID=$REMOTE_DST_EID


    export DEST_EID=$EID
    export DEST_VAULT_ADDRESS=$VAULT_ADDRESS
fi