source  dev-scripts/crosschain/env.sh

echo "CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS: $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS"
echo "CURRENT_DST_EID: $CURRENT_DST_EID"



cast send $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS "setRemoteVault(uint32,address)" $CURRENT_DST_EID $CURRENT_DST_VAULT_ADDRESS --rpc-url $RPC_URL --private-key $PRIVATE_KEY