source dev-scripts/crosschain/env.sh

echo "CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS: $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS"
echo "CURRENT_TOKEN_ADDRESS: $CURRENT_TOKEN_ADDRESS"
echo "CURRENT_OFT_ADDRESS: $CURRENT_OFT_ADDRESS"
echo "RPC_URL: $RPC_URL"

cast send $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS "setTokenConfig(address,address)" $CURRENT_TOKEN_ADDRESS $CURRENT_OFT_ADDRESS --rpc-url $RPC_URL --private-key $PRIVATE_KEY