# source dev-scripts/current-env.sh

echo "CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS: $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS"
echo "CURRENT_ASSET_ADDRESS: $CURRENT_ASSET_ADDRESS"
echo "CURRENT_OFT_ADDRESS: $CURRENT_OFT_ADDRESS"
echo "RPC_URL: $RPC_URL"

cast send $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS "setTokenConfig(address,address)" $CURRENT_ASSET_ADDRESS $CURRENT_OFT_ADDRESS --rpc-url $RPC_URL --private-key $PRIVATE_KEY