# source  dev-scripts/current-env.sh

echo "CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS: $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS"
echo "DEST_EID: $DEST_EID"
echo "DEST_VAULT_ADDRESS: $DEST_VAULT_ADDRESS"

cast send $CURRENT_CROSSCHAIN_STRATEGY_ADAPTER_ADDRESS "setRemoteVault(uint32,address)" $DEST_EID $DEST_VAULT_ADDRESS --rpc-url $RPC_URL --private-key $PRIVATE_KEY